Use python-ipaddress and python-twisted from meta-openembedded layer [YOCIMX-3039]
There were install conflicts:
Error: Transaction check error:
  file /usr/lib/python2.7/site-packages/ipaddress.py conflicts between attempted installs of python-ipaddress-1.0.19-r0.cortexa7hf_neon and py2-ipaddress-3.4.1-r0.cortexa7hf_neon
  file /usr/lib/python2.7/site-packages/ipaddress.pyc conflicts between attempted installs of python-ipaddress-1.0.19-r0.cortexa7hf_neon and py2-ipaddress-3.4.1-r0.cortexa7hf_neon

Signed-off-by: Cristinel Panfir <cristinel.panfir@nxp.com>