polkit: change group owner for rules.d [YOCIMX-2413]
Fix install conflicts btw polkit and polkit-group-rule-network or
polkit-group-rule-datetime packages.

Errors reported at do_rootfs:

Error: Transaction check error:
  file /etc/polkit-1/rules.d from install of polkit-0.113-r0.cortexa7hf_neon
conflicts with file from package polkit-group-rule-datetime-1.0-r0.cortexa7hf_neon
  file /etc/polkit-1/rules.d from install of polkit-0.113-r0.cortexa7hf_neon
conflicts with file from package polkit-group-rule-network-1.0-r0.cortexa7hf_neon

Signed-off-by: Cristinel Panfir <cristinel.panfir@nxp.com>